### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ypriverol** [ypriverol/pIR#3]
@enriquea We should try to work around the performance issues. It would be great if this 60000 peptides can run in less time, please review the Bjel methods steps of the algorithm and also in the iterative algorithm.

**Comment by enriquea** [comment]
Hi @ypriverol Both Bjell and Iterative method were changed to improve the performance. You could check the changes done here: https://github.com/enriquea/pIR. You could test it running the following commands:

> branca <- read.table(file = "data/ruiBrancaDataSet.csv", header = TRUE, sep = ",")
> data <- mdply(branca, function(sequence, pIExp) { pIBjell(sequence = sequence, pkSetMethod = "expasy") })

In the present version the performance was improved 5X. 

Let me know how it works for you,

Best regards

**Comment by ypriverol** [comment]
@enriquea Can we test the SVM to see how it works.

**Comment by ypriverol** [comment]
the closed pull-request solve all the performance issues. https://github.com/ypriverol/pIR/pull/10
